import java.util.Scanner;

/**
 * Created by vardan sharma on 15/4/16.
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7'th
 * triangle number would be 1+2+3+4+5+6+7=28. The first ten terms would be:
 *
 * 1,3,6,10,15,21,28,36,45,55
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1:1
 * 3:1,3
 * 6:1,2,3,
 * 10:1,2,5,
 * 15:1,3,5,15
 * 21:1,3,7,21
 * 28:1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over N divisors?
 *
 * Input
 * First line T, the number of testcases. Each testcase consists of N in one line.
 *
 * Output
 * For each testcase, print the required answer in one line.
 *
 * Constraints
 * 1≤T≤10
 * 1≤N≤10^3
 */
public class Problem12 {
  public static void main(String[] args) {
    //Scanner scanner = new Scanner(System.in);
    //int t = scanner.nextInt();
    //for (int i = 0; i < t; i++) {
    //  System.out.println(calculate(scanner.nextInt()));
    //}
    System.out.println(calculate(2));
  }

  private static int calculate(int i) {
    for (int j = 0; j < Integer.MAX_VALUE; j++) {
      System.out.println(j);
      if (numFactors(triangleNumber(j)) >= i) return j;
    }
    return -1;
  }

  private static int triangleNumber(int n) {
    return (n * (n + 1)) / 2;
  }

  private static int numFactors(int n) {
    int ans = 0;
    for (int i = 1; i < n; i++) {
      if (n % i == 0) ans++;
    }
    return ans;
  }
}
